package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ê³„ì • ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AccountVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?šŒ?›ë²ˆí˜¸. */
	private Integer num;

	/** ?•„?´?””. */
	private String id;

	/** ë¹„ë?ë²ˆí˜¸. */
	private String pwd;

	/** ì°¸ì—¬?¸?›? •ë³? ëª©ë¡. */
	private Set<AttendinfoVo> attendinfoSet;

	/** ?‹¬? ¥ ëª©ë¡. */
	private Set<CalenderVo> calenderSet;

	/** ì½”ë©˜?Š¸ ëª©ë¡. */
	private Set<CommentVo> commentSet;

	/** ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡. */
	private Set<EmoticongroupVo> emoticongroupSet;

	/** ì°œëª©ë¡? ëª©ë¡. */
	private Set<FavorlistVo> favorlistSet;

	/** ì¹œêµ¬ëª©ë¡ ëª©ë¡. */
	private Set<FriendlistVo> friendlistSet;

	/** ?˜µ?…˜ ëª©ë¡. */
	private Set<OptionVo> optionSet;

	/** ?„ ë¬? ëª©ë¡. */
	private Set<PresentVo> presentSet;

	/** ?”„ë¡œí•„ ëª©ë¡. */
	private Set<ProfileVo> profileSet;

	/** ë¬¸ì˜ ëª©ë¡. */
	private Set<QnaVo> qnaSet;

	/** ?Š¤?† ë¦? ëª©ë¡. */
	private Set<StoryVo> storySet;

	/**
	 * ?ƒ?„±?.
	 */
	public AccountVo() {
		this.attendinfoSet = new HashSet<AttendinfoVo>();
		this.calenderSet = new HashSet<CalenderVo>();
		this.commentSet = new HashSet<CommentVo>();
		this.emoticongroupSet = new HashSet<EmoticongroupVo>();
		this.favorlistSet = new HashSet<FavorlistVo>();
		this.friendlistSet = new HashSet<FriendlistVo>();
		this.optionSet = new HashSet<OptionVo>();
		this.presentSet = new HashSet<PresentVo>();
		this.profileSet = new HashSet<ProfileVo>();
		this.qnaSet = new HashSet<QnaVo>();
		this.storySet = new HashSet<StoryVo>();
	}

	/**
	 * ?šŒ?›ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param num
	 *            ?šŒ?›ë²ˆí˜¸
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * ?šŒ?›ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?šŒ?›ë²ˆí˜¸
	 */
	public Integer getNum() {
		return this.num;
	}

	/**
	 * ?•„?´?””?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param id
	 *            ?•„?´?””
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * ?•„?´?””?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?•„?´?””
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * ë¹„ë?ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param pwd
	 *            ë¹„ë?ë²ˆí˜¸
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * ë¹„ë?ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¹„ë?ë²ˆí˜¸
	 */
	public String getPwd() {
		return this.pwd;
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param attendinfoSet
	 *            ì°¸ì—¬?¸?›? •ë³? ëª©ë¡
	 */
	public void setAttendinfoSet(Set<AttendinfoVo> attendinfoSet) {
		this.attendinfoSet = attendinfoSet;
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³´ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param attendinfo
	 *            ì°¸ì—¬?¸?›? •ë³?
	 */
	public void addAttendinfo(AttendinfoVo attendinfo) {
		this.attendinfoSet.add(attendinfo);
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°¸ì—¬?¸?›? •ë³? ëª©ë¡
	 */
	public Set<AttendinfoVo> getAttendinfoSet() {
		return this.attendinfoSet;
	}

	/**
	 * ?‹¬? ¥ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param calenderSet
	 *            ?‹¬? ¥ ëª©ë¡
	 */
	public void setCalenderSet(Set<CalenderVo> calenderSet) {
		this.calenderSet = calenderSet;
	}

	/**
	 * ?‹¬? ¥ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param calender
	 *            ?‹¬? ¥
	 */
	public void addCalender(CalenderVo calender) {
		this.calenderSet.add(calender);
	}

	/**
	 * ?‹¬? ¥ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?‹¬? ¥ ëª©ë¡
	 */
	public Set<CalenderVo> getCalenderSet() {
		return this.calenderSet;
	}

	/**
	 * ì½”ë©˜?Š¸ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commentSet
	 *            ì½”ë©˜?Š¸ ëª©ë¡
	 */
	public void setCommentSet(Set<CommentVo> commentSet) {
		this.commentSet = commentSet;
	}

	/**
	 * ì½”ë©˜?Š¸ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param comment
	 *            ì½”ë©˜?Š¸
	 */
	public void addComment(CommentVo comment) {
		this.commentSet.add(comment);
	}

	/**
	 * ì½”ë©˜?Š¸ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸ ëª©ë¡
	 */
	public Set<CommentVo> getCommentSet() {
		return this.commentSet;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoticongroupSet
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡
	 */
	public void setEmoticongroupSet(Set<EmoticongroupVo> emoticongroupSet) {
		this.emoticongroupSet = emoticongroupSet;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param emoticongroup
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£?
	 */
	public void addEmoticongroup(EmoticongroupVo emoticongroup) {
		this.emoticongroupSet.add(emoticongroup);
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡
	 */
	public Set<EmoticongroupVo> getEmoticongroupSet() {
		return this.emoticongroupSet;
	}

	/**
	 * ì°œëª©ë¡? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favorlistSet
	 *            ì°œëª©ë¡? ëª©ë¡
	 */
	public void setFavorlistSet(Set<FavorlistVo> favorlistSet) {
		this.favorlistSet = favorlistSet;
	}

	/**
	 * ì°œëª©ë¡ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param favorlist
	 *            ì°œëª©ë¡?
	 */
	public void addFavorlist(FavorlistVo favorlist) {
		this.favorlistSet.add(favorlist);
	}

	/**
	 * ì°œëª©ë¡? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°œëª©ë¡? ëª©ë¡
	 */
	public Set<FavorlistVo> getFavorlistSet() {
		return this.favorlistSet;
	}

	/**
	 * ì¹œêµ¬ëª©ë¡ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param friendlistSet
	 *            ì¹œêµ¬ëª©ë¡ ëª©ë¡
	 */
	public void setFriendlistSet(Set<FriendlistVo> friendlistSet) {
		this.friendlistSet = friendlistSet;
	}

	/**
	 * ì¹œêµ¬ëª©ë¡ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param friendlist
	 *            ì¹œêµ¬ëª©ë¡
	 */
	public void addFriendlist(FriendlistVo friendlist) {
		this.friendlistSet.add(friendlist);
	}

	/**
	 * ì¹œêµ¬ëª©ë¡ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì¹œêµ¬ëª©ë¡ ëª©ë¡
	 */
	public Set<FriendlistVo> getFriendlistSet() {
		return this.friendlistSet;
	}

	/**
	 * ?˜µ?…˜ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param optionSet
	 *            ?˜µ?…˜ ëª©ë¡
	 */
	public void setOptionSet(Set<OptionVo> optionSet) {
		this.optionSet = optionSet;
	}

	/**
	 * ?˜µ?…˜ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param option
	 *            ?˜µ?…˜
	 */
	public void addOption(OptionVo option) {
		this.optionSet.add(option);
	}

	/**
	 * ?˜µ?…˜ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?˜µ?…˜ ëª©ë¡
	 */
	public Set<OptionVo> getOptionSet() {
		return this.optionSet;
	}

	/**
	 * ?„ ë¬? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param presentSet
	 *            ?„ ë¬? ëª©ë¡
	 */
	public void setPresentSet(Set<PresentVo> presentSet) {
		this.presentSet = presentSet;
	}

	/**
	 * ?„ ë¬¼ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param present
	 *            ?„ ë¬?
	 */
	public void addPresent(PresentVo present) {
		this.presentSet.add(present);
	}

	/**
	 * ?„ ë¬? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?„ ë¬? ëª©ë¡
	 */
	public Set<PresentVo> getPresentSet() {
		return this.presentSet;
	}


	/**
	 * ?”„ë¡œí•„ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param profileSet
	 *            ?”„ë¡œí•„ ëª©ë¡
	 */
	public void setProfileSet(Set<ProfileVo> profileSet) {
		this.profileSet = profileSet;
	}

	/**
	 * ?”„ë¡œí•„ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param profile
	 *            ?”„ë¡œí•„
	 */
	public void addProfile(ProfileVo profile) {
		this.profileSet.add(profile);
	}

	/**
	 * ?”„ë¡œí•„ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?”„ë¡œí•„ ëª©ë¡
	 */
	public Set<ProfileVo> getProfileSet() {
		return this.profileSet;
	}

	/**
	 * ë¬¸ì˜ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnaSet
	 *            ë¬¸ì˜ ëª©ë¡
	 */
	public void setQnaSet(Set<QnaVo> qnaSet) {
		this.qnaSet = qnaSet;
	}

	/**
	 * ë¬¸ì˜ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param qna
	 *            ë¬¸ì˜
	 */
	public void addQna(QnaVo qna) {
		this.qnaSet.add(qna);
	}

	/**
	 * ë¬¸ì˜ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜ ëª©ë¡
	 */
	public Set<QnaVo> getQnaSet() {
		return this.qnaSet;
	}

	/**
	 * ?Š¤?† ë¦? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param storySet
	 *            ?Š¤?† ë¦? ëª©ë¡
	 */
	public void setStorySet(Set<StoryVo> storySet) {
		this.storySet = storySet;
	}

	/**
	 * ?Š¤?† ë¦¬ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param story
	 *            ?Š¤?† ë¦?
	 */
	public void addStory(StoryVo story) {
		this.storySet.add(story);
	}

	/**
	 * ?Š¤?† ë¦? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¤?† ë¦? ëª©ë¡
	 */
	public Set<StoryVo> getStorySet() {
		return this.storySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((num == null) ? 0 : num.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AccountVo other = (AccountVo) obj;
		if (num == null) {
			if (other.num != null) {
				return false;
			}
		} else if (!num.equals(other.num)) {
			return false;
		}
		return true;
	}

}
