package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;

/**
 * 광고 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AdVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 광고번호. */
	private Integer adnum;

	/** 광고이름. */
	private String adname;

	/** 광고원본이미지이름. */
	private String adorgimg;

	/** 광고저장이미지이름. */
	private String adsaveimg;

	/** 광고파일크기. */
	private Blob adimgsize;

	/** 광고등록일자. */
	private Date addadregdate;

	/** 광고만료일자. */
	private Date deladregdate;

	/**
	 * 생성자.
	 */
	public AdVo() {
	}

	/**
	 * 광고번호을 설정합니다..
	 * 
	 * @param adnum
	 *            광고번호
	 */
	public void setAdnum(Integer adnum) {
		this.adnum = adnum;
	}

	/**
	 * 광고번호을 가져옵니다..
	 * 
	 * @return 광고번호
	 */
	public Integer getAdnum() {
		return this.adnum;
	}

	/**
	 * 광고이름을 설정합니다..
	 * 
	 * @param adname
	 *            광고이름
	 */
	public void setAdname(String adname) {
		this.adname = adname;
	}

	/**
	 * 광고이름을 가져옵니다..
	 * 
	 * @return 광고이름
	 */
	public String getAdname() {
		return this.adname;
	}

	/**
	 * 광고원본이미지이름을 설정합니다..
	 * 
	 * @param adorgimg
	 *            광고원본이미지이름
	 */
	public void setAdorgimg(String adorgimg) {
		this.adorgimg = adorgimg;
	}

	/**
	 * 광고원본이미지이름을 가져옵니다..
	 * 
	 * @return 광고원본이미지이름
	 */
	public String getAdorgimg() {
		return this.adorgimg;
	}

	/**
	 * 광고저장이미지이름을 설정합니다..
	 * 
	 * @param adsaveimg
	 *            광고저장이미지이름
	 */
	public void setAdsaveimg(String adsaveimg) {
		this.adsaveimg = adsaveimg;
	}

	/**
	 * 광고저장이미지이름을 가져옵니다..
	 * 
	 * @return 광고저장이미지이름
	 */
	public String getAdsaveimg() {
		return this.adsaveimg;
	}

	/**
	 * 광고파일크기을 설정합니다..
	 * 
	 * @param adimgsize
	 *            광고파일크기
	 */
	public void setAdimgsize(Blob adimgsize) {
		this.adimgsize = adimgsize;
	}

	/**
	 * 광고파일크기을 가져옵니다..
	 * 
	 * @return 광고파일크기
	 */
	public Blob getAdimgsize() {
		return this.adimgsize;
	}

	/**
	 * 광고등록일자을 설정합니다..
	 * 
	 * @param addadregdate
	 *            광고등록일자
	 */
	public void setAddadregdate(Date addadregdate) {
		this.addadregdate = addadregdate;
	}

	/**
	 * 광고등록일자을 가져옵니다..
	 * 
	 * @return 광고등록일자
	 */
	public Date getAddadregdate() {
		return this.addadregdate;
	}

	/**
	 * 광고만료일자을 설정합니다..
	 * 
	 * @param deladregdate
	 *            광고만료일자
	 */
	public void setDeladregdate(Date deladregdate) {
		this.deladregdate = deladregdate;
	}

	/**
	 * 광고만료일자을 가져옵니다..
	 * 
	 * @return 광고만료일자
	 */
	public Date getDeladregdate() {
		return this.deladregdate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adnum == null) ? 0 : adnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AdVo other = (AdVo) obj;
		if (adnum == null) {
			if (other.adnum != null) {
				return false;
			}
		} else if (!adnum.equals(other.adnum)) {
			return false;
		}
		return true;
	}

}
