package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;

/**
 * ê´‘ê³  ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AdVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ê´‘ê³ ë²ˆí˜¸. */
	private Integer adnum;

	/** ê´‘ê³ ?´ë¦?. */
	private String adname;

	/** ê´‘ê³ ?›ë³¸ì´ë¯¸ì??´ë¦?. */
	private String adorgimg;

	/** ê´‘ê³ ???¥?´ë¯¸ì??´ë¦?. */
	private String adsaveimg;

	/** ê´‘ê³ ?ŒŒ?¼?¬ê¸?. */
	private Blob adimgsize;

	/** ê´‘ê³ ?“±ë¡ì¼?. */
	private Date addadregdate;

	/** ê´‘ê³ ë§Œë£Œ?¼?. */
	private Date deladregdate;

	/**
	 * ?ƒ?„±?.
	 */
	public AdVo() {
	}

	/**
	 * ê´‘ê³ ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param adnum
	 *            ê´‘ê³ ë²ˆí˜¸
	 */
	public void setAdnum(Integer adnum) {
		this.adnum = adnum;
	}

	/**
	 * ê´‘ê³ ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ë²ˆí˜¸
	 */
	public Integer getAdnum() {
		return this.adnum;
	}

	/**
	 * ê´‘ê³ ?´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param adname
	 *            ê´‘ê³ ?´ë¦?
	 */
	public void setAdname(String adname) {
		this.adname = adname;
	}

	/**
	 * ê´‘ê³ ?´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ?´ë¦?
	 */
	public String getAdname() {
		return this.adname;
	}

	/**
	 * ê´‘ê³ ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param adorgimg
	 *            ê´‘ê³ ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public void setAdorgimg(String adorgimg) {
		this.adorgimg = adorgimg;
	}

	/**
	 * ê´‘ê³ ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public String getAdorgimg() {
		return this.adorgimg;
	}

	/**
	 * ê´‘ê³ ???¥?´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param adsaveimg
	 *            ê´‘ê³ ???¥?´ë¯¸ì??´ë¦?
	 */
	public void setAdsaveimg(String adsaveimg) {
		this.adsaveimg = adsaveimg;
	}

	/**
	 * ê´‘ê³ ???¥?´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ???¥?´ë¯¸ì??´ë¦?
	 */
	public String getAdsaveimg() {
		return this.adsaveimg;
	}

	/**
	 * ê´‘ê³ ?ŒŒ?¼?¬ê¸°ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param adimgsize
	 *            ê´‘ê³ ?ŒŒ?¼?¬ê¸?
	 */
	public void setAdimgsize(Blob adimgsize) {
		this.adimgsize = adimgsize;
	}

	/**
	 * ê´‘ê³ ?ŒŒ?¼?¬ê¸°ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ?ŒŒ?¼?¬ê¸?
	 */
	public Blob getAdimgsize() {
		return this.adimgsize;
	}

	/**
	 * ê´‘ê³ ?“±ë¡ì¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param addadregdate
	 *            ê´‘ê³ ?“±ë¡ì¼?
	 */
	public void setAddadregdate(Date addadregdate) {
		this.addadregdate = addadregdate;
	}

	/**
	 * ê´‘ê³ ?“±ë¡ì¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ?“±ë¡ì¼?
	 */
	public Date getAddadregdate() {
		return this.addadregdate;
	}

	/**
	 * ê´‘ê³ ë§Œë£Œ?¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param deladregdate
	 *            ê´‘ê³ ë§Œë£Œ?¼?
	 */
	public void setDeladregdate(Date deladregdate) {
		this.deladregdate = deladregdate;
	}

	/**
	 * ê´‘ê³ ë§Œë£Œ?¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê´‘ê³ ë§Œë£Œ?¼?
	 */
	public Date getDeladregdate() {
		return this.deladregdate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adnum == null) ? 0 : adnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AdVo other = (AdVo) obj;
		if (adnum == null) {
			if (other.adnum != null) {
				return false;
			}
		} else if (!adnum.equals(other.adnum)) {
			return false;
		}
		return true;
	}

}
