package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ì°¸ì—¬?¸?›? •ë³? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AttendinfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì±„íŒ…ë¦¬ìŠ¤?Š¸. */
	private ChatlistVo chatlist;

	/** ê³„ì •. */
	private AccountVo account;

	/** ?šŒ?›?ƒ?ƒœ. */
	private Integer state;

	/** ì±„íŒ… ëª©ë¡. */
	private Set<ChatVo> chatSet;

	/** ì±„íŒ…ë°©ìƒ?ƒœ ëª©ë¡. */
	private Set<ChatstateVo> chatstateSet;

	/** ê³µì? ëª©ë¡. */
	private Set<NoticeVo> noticeSet;


	/**
	 * ?ƒ?„±?.
	 */
	public AttendinfoVo() {
		this.chatSet = new HashSet<ChatVo>();
		this.chatstateSet = new HashSet<ChatstateVo>();
		this.noticeSet = new HashSet<NoticeVo>();
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatlist
	 *            ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public void setChatlist(ChatlistVo chatlist) {
		this.chatlist = chatlist;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public ChatlistVo getChatlist() {
		return this.chatlist;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ?šŒ?›?ƒ?ƒœ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param state
	 *            ?šŒ?›?ƒ?ƒœ
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * ?šŒ?›?ƒ?ƒœ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?šŒ?›?ƒ?ƒœ
	 */
	public Integer getState() {
		return this.state;
	}

	/**
	 * ì±„íŒ… ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatSet
	 *            ì±„íŒ… ëª©ë¡
	 */
	public void setChatSet(Set<ChatVo> chatSet) {
		this.chatSet = chatSet;
	}

	/**
	 * ì±„íŒ…ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param chat
	 *            ì±„íŒ…
	 */
	public void addChat(ChatVo chat) {
		this.chatSet.add(chat);
	}

	/**
	 * ì±„íŒ… ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ… ëª©ë¡
	 */
	public Set<ChatVo> getChatSet() {
		return this.chatSet;
	}

	/**
	 * ì±„íŒ…ë°©ìƒ?ƒœ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatstateSet
	 *            ì±„íŒ…ë°©ìƒ?ƒœ ëª©ë¡
	 */
	public void setChatstateSet(Set<ChatstateVo> chatstateSet) {
		this.chatstateSet = chatstateSet;
	}

	/**
	 * ì±„íŒ…ë°©ìƒ?ƒœë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param chatstate
	 *            ì±„íŒ…ë°©ìƒ?ƒœ
	 */
	public void addChatstate(ChatstateVo chatstate) {
		this.chatstateSet.add(chatstate);
	}

	/**
	 * ì±„íŒ…ë°©ìƒ?ƒœ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë°©ìƒ?ƒœ ëª©ë¡
	 */
	public Set<ChatstateVo> getChatstateSet() {
		return this.chatstateSet;
	}

	/**
	 * ê³µì? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param noticeSet
	 *            ê³µì? ëª©ë¡
	 */
	public void setNoticeSet(Set<NoticeVo> noticeSet) {
		this.noticeSet = noticeSet;
	}

	/**
	 * ê³µì?ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param notice
	 *            ê³µì?
	 */
	public void addNotice(NoticeVo notice) {
		this.noticeSet.add(notice);
	}

	/**
	 * ê³µì? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³µì? ëª©ë¡
	 */
	public Set<NoticeVo> getNoticeSet() {
		return this.noticeSet;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chatlist == null) ? 0 : chatlist.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AttendinfoVo other = (AttendinfoVo) obj;
		if (chatlist == null) {
			if (other.chatlist != null) {
				return false;
			}
		} else if (!chatlist.equals(other.chatlist)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
