package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 달력 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CalenderVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 기념일번호. */
	private Integer anivernum;

	/** 계정. */
	private AccountVo account;

	/** 기념일이름. */
	private String anivername;

	/** 기념일날짜. */
	private Date aniverregdate;

	/** 기념일내용. */
	private String anivercontent;

	/** 기념일상태. */
	private Integer aniverstate;

	/** 알람. */
	private Integer alarm;

	/**
	 * 생성자.
	 */
	public CalenderVo() {
	}

	/**
	 * 기념일번호을 설정합니다..
	 * 
	 * @param anivernum
	 *            기념일번호
	 */
	public void setAnivernum(Integer anivernum) {
		this.anivernum = anivernum;
	}

	/**
	 * 기념일번호을 가져옵니다..
	 * 
	 * @return 기념일번호
	 */
	public Integer getAnivernum() {
		return this.anivernum;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * 기념일이름을 설정합니다..
	 * 
	 * @param anivername
	 *            기념일이름
	 */
	public void setAnivername(String anivername) {
		this.anivername = anivername;
	}

	/**
	 * 기념일이름을 가져옵니다..
	 * 
	 * @return 기념일이름
	 */
	public String getAnivername() {
		return this.anivername;
	}

	/**
	 * 기념일날짜을 설정합니다..
	 * 
	 * @param aniverregdate
	 *            기념일날짜
	 */
	public void setAniverregdate(Date aniverregdate) {
		this.aniverregdate = aniverregdate;
	}

	/**
	 * 기념일날짜을 가져옵니다..
	 * 
	 * @return 기념일날짜
	 */
	public Date getAniverregdate() {
		return this.aniverregdate;
	}

	/**
	 * 기념일내용을 설정합니다..
	 * 
	 * @param anivercontent
	 *            기념일내용
	 */
	public void setAnivercontent(String anivercontent) {
		this.anivercontent = anivercontent;
	}

	/**
	 * 기념일내용을 가져옵니다..
	 * 
	 * @return 기념일내용
	 */
	public String getAnivercontent() {
		return this.anivercontent;
	}

	/**
	 * 기념일상태을 설정합니다..
	 * 
	 * @param aniverstate
	 *            기념일상태
	 */
	public void setAniverstate(Integer aniverstate) {
		this.aniverstate = aniverstate;
	}

	/**
	 * 기념일상태을 가져옵니다..
	 * 
	 * @return 기념일상태
	 */
	public Integer getAniverstate() {
		return this.aniverstate;
	}

	/**
	 * 알람을 설정합니다..
	 * 
	 * @param alarm
	 *            알람
	 */
	public void setAlarm(Integer alarm) {
		this.alarm = alarm;
	}

	/**
	 * 알람을 가져옵니다..
	 * 
	 * @return 알람
	 */
	public Integer getAlarm() {
		return this.alarm;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((anivernum == null) ? 0 : anivernum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CalenderVo other = (CalenderVo) obj;
		if (anivernum == null) {
			if (other.anivernum != null) {
				return false;
			}
		} else if (!anivernum.equals(other.anivernum)) {
			return false;
		}
		return true;
	}

}
