package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ì±„íŒ…ë¦¬ìŠ¤?Š¸ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ChatlistVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì±„íŒ…ë°©ë²ˆ?˜¸. */
	private Integer clnum;

	/** ì±„íŒ…ë°©ì´ë¦?. */
	private String name;

	/** ì°¸ì—¬?¸?›? •ë³? ëª©ë¡. */
	private Set<AttendinfoVo> attendinfoSet;

	/**
	 * ?ƒ?„±?.
	 */
	public ChatlistVo() {
		this.attendinfoSet = new HashSet<AttendinfoVo>();
	}

	/**
	 * ì±„íŒ…ë°©ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param clnum
	 *            ì±„íŒ…ë°©ë²ˆ?˜¸
	 */
	public void setClnum(Integer clnum) {
		this.clnum = clnum;
	}

	/**
	 * ì±„íŒ…ë°©ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë°©ë²ˆ?˜¸
	 */
	public Integer getClnum() {
		return this.clnum;
	}

	/**
	 * ì±„íŒ…ë°©ì´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param name
	 *            ì±„íŒ…ë°©ì´ë¦?
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * ì±„íŒ…ë°©ì´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë°©ì´ë¦?
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param attendinfoSet
	 *            ì°¸ì—¬?¸?›? •ë³? ëª©ë¡
	 */
	public void setAttendinfoSet(Set<AttendinfoVo> attendinfoSet) {
		this.attendinfoSet = attendinfoSet;
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³´ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param attendinfo
	 *            ì°¸ì—¬?¸?›? •ë³?
	 */
	public void addAttendinfo(AttendinfoVo attendinfo) {
		this.attendinfoSet.add(attendinfo);
	}

	/**
	 * ì°¸ì—¬?¸?›? •ë³? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°¸ì—¬?¸?›? •ë³? ëª©ë¡
	 */
	public Set<AttendinfoVo> getAttendinfoSet() {
		return this.attendinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clnum == null) ? 0 : clnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ChatlistVo other = (ChatlistVo) obj;
		if (clnum == null) {
			if (other.clnum != null) {
				return false;
			}
		} else if (!clnum.equals(other.clnum)) {
			return false;
		}
		return true;
	}

}
