package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ì±„íŒ…ë°©ìƒ?ƒœ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ChatstateVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?•Œ?Œ. */
	private Integer alarm;

	/** ì¦ê²¨ì°¾ê¸°. */
	private Integer favo;

	/** ì±„íŒ…ë¦¬ìŠ¤?Š¸. */
	private ChatlistVo chatlist;

	/** ê³„ì •. */
	private AccountVo account;

	/**
	 * ?ƒ?„±?.
	 */
	public ChatstateVo() {
	}

	/**
	 * ?•Œ?Œ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param alarm
	 *            ?•Œ?Œ
	 */
	public void setAlarm(Integer alarm) {
		this.alarm = alarm;
	}

	/**
	 * ?•Œ?Œ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?•Œ?Œ
	 */
	public Integer getAlarm() {
		return this.alarm;
	}

	/**
	 * ì¦ê²¨ì°¾ê¸°?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favo
	 *            ì¦ê²¨ì°¾ê¸°
	 */
	public void setFavo(Integer favo) {
		this.favo = favo;
	}

	/**
	 * ì¦ê²¨ì°¾ê¸°?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì¦ê²¨ì°¾ê¸°
	 */
	public Integer getFavo() {
		return this.favo;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatlist
	 *            ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public void setChatlist(ChatlistVo chatlist) {
		this.chatlist = chatlist;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public ChatlistVo getChatlist() {
		return this.chatlist;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chatlist == null) ? 0 : chatlist.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ChatstateVo other = (ChatstateVo) obj;
		if (chatlist == null) {
			if (other.chatlist != null) {
				return false;
			}
		} else if (!chatlist.equals(other.chatlist)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
