package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 채팅리스트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ChatlistVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 채팅방번호. */
	private Integer clnum;

	/** 채팅방이름. */
	private String name;

	/** 참여인원정보 목록. */
	private Set<AttendinfoVo> attendinfoSet;

	/**
	 * 생성자.
	 */
	public ChatlistVo() {
		this.attendinfoSet = new HashSet<AttendinfoVo>();
	}

	/**
	 * 채팅방번호을 설정합니다..
	 * 
	 * @param clnum
	 *            채팅방번호
	 */
	public void setClnum(Integer clnum) {
		this.clnum = clnum;
	}

	/**
	 * 채팅방번호을 가져옵니다..
	 * 
	 * @return 채팅방번호
	 */
	public Integer getClnum() {
		return this.clnum;
	}

	/**
	 * 채팅방이름을 설정합니다..
	 * 
	 * @param name
	 *            채팅방이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 채팅방이름을 가져옵니다..
	 * 
	 * @return 채팅방이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 참여인원정보 목록을 설정합니다..
	 * 
	 * @param attendinfoSet
	 *            참여인원정보 목록
	 */
	public void setAttendinfoSet(Set<AttendinfoVo> attendinfoSet) {
		this.attendinfoSet = attendinfoSet;
	}

	/**
	 * 참여인원정보를 추가합니다..
	 * 
	 * @param attendinfo
	 *            참여인원정보
	 */
	public void addAttendinfo(AttendinfoVo attendinfo) {
		this.attendinfoSet.add(attendinfo);
	}

	/**
	 * 참여인원정보 목록을 가져옵니다..
	 * 
	 * @return 참여인원정보 목록
	 */
	public Set<AttendinfoVo> getAttendinfoSet() {
		return this.attendinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clnum == null) ? 0 : clnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ChatlistVo other = (ChatlistVo) obj;
		if (clnum == null) {
			if (other.clnum != null) {
				return false;
			}
		} else if (!clnum.equals(other.clnum)) {
			return false;
		}
		return true;
	}

}
