package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ì±„íŒ… ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ChatVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì±„íŒ…ë²ˆí˜¸. */
	private Integer cnum;

	/** ?ƒ?ƒœ. */
	private Integer state;

	/** ?‚´?š©. */
	private String content;

	/** ?‘?„±?¼?. */
	private Date regdate;

	/** ?´ëª¨í‹°ì½˜ë²ˆ?˜¸. */
	private Integer emoticonnum;

	/** ?›ë³¸ì´ë¯¸ì??´ë¦?. */
	private String orgimg;

	/** ???¥?´ë¯¸ì??´ë¦?. */
	private String saveimg;

	/** ?ŒŒ?¼?¬ê¸?. */
	private Blob imgsize;

	/** ì±„íŒ…ë¦¬ìŠ¤?Š¸. */
	private ChatlistVo chatlist;

	/** ê³„ì •. */
	private AccountVo account;

	/** ?½???‚¬?Œ? •ë³? ëª©ë¡. */
	private Set<NoticeVo> noticeSet;

	/**
	 * ?ƒ?„±?.
	 */
	public ChatVo() {
		this.noticeSet = new HashSet<NoticeVo>();
	}

	/**
	 * ì±„íŒ…ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param cnum
	 *            ì±„íŒ…ë²ˆí˜¸
	 */
	public void setCnum(Integer cnum) {
		this.cnum = cnum;
	}

	/**
	 * ì±„íŒ…ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë²ˆí˜¸
	 */
	public Integer getCnum() {
		return this.cnum;
	}

	/**
	 * ?ƒ?ƒœ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param state
	 *            ?ƒ?ƒœ
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * ?ƒ?ƒœ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?ƒ?ƒœ
	 */
	public Integer getState() {
		return this.state;
	}

	/**
	 * ?‚´?š©?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param content
	 *            ?‚´?š©
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * ?‚´?š©?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?‚´?š©
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * ?‘?„±?¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param regdate
	 *            ?‘?„±?¼?
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * ?‘?„±?¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?‘?„±?¼?
	 */
	public Date getRegdate() {
		return this.regdate;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoticonnum
	 *            ?´ëª¨í‹°ì½˜ë²ˆ?˜¸
	 */
	public void setEmoticonnum(Integer emoticonnum) {
		this.emoticonnum = emoticonnum;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ë²ˆ?˜¸
	 */
	public Integer getEmoticonnum() {
		return this.emoticonnum;
	}

	/**
	 * ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param orgimg
	 *            ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public void setOrgimg(String orgimg) {
		this.orgimg = orgimg;
	}

	/**
	 * ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public String getOrgimg() {
		return this.orgimg;
	}

	/**
	 * ???¥?´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param saveimg
	 *            ???¥?´ë¯¸ì??´ë¦?
	 */
	public void setSaveimg(String saveimg) {
		this.saveimg = saveimg;
	}

	/**
	 * ???¥?´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ???¥?´ë¯¸ì??´ë¦?
	 */
	public String getSaveimg() {
		return this.saveimg;
	}

	/**
	 * ?ŒŒ?¼?¬ê¸°ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param imgsize
	 *            ?ŒŒ?¼?¬ê¸?
	 */
	public void setImgsize(Blob imgsize) {
		this.imgsize = imgsize;
	}

	/**
	 * ?ŒŒ?¼?¬ê¸°ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?ŒŒ?¼?¬ê¸?
	 */
	public Blob getImgsize() {
		return this.imgsize;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatlist
	 *            ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public void setChatlist(ChatlistVo chatlist) {
		this.chatlist = chatlist;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public ChatlistVo getChatlist() {
		return this.chatlist;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ?½???‚¬?Œ? •ë³? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param noticeSet
	 *            ?½???‚¬?Œ? •ë³? ëª©ë¡
	 */
	public void setNoticeSet(Set<NoticeVo> noticeSet) {
		this.noticeSet = noticeSet;
	}

	/**
	 * ?½???‚¬?Œ? •ë³´ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param notice
	 *            ?½???‚¬?Œ? •ë³?
	 */
	public void addNotice(NoticeVo notice) {
		this.noticeSet.add(notice);
	}

	/**
	 * ?½???‚¬?Œ? •ë³? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?½???‚¬?Œ? •ë³? ëª©ë¡
	 */
	public Set<NoticeVo> getNoticeSet() {
		return this.noticeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cnum == null) ? 0 : cnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ChatVo other = (ChatVo) obj;
		if (cnum == null) {
			if (other.cnum != null) {
				return false;
			}
		} else if (!cnum.equals(other.cnum)) {
			return false;
		}
		return true;
	}

}
