package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ì½”ë©˜?Š¸ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì½”ë©˜?Š¸ë²ˆí˜¸. */
	private Integer commnum;

	/** ?Š¤?† ë¦?. */
	private StoryVo story;

	/** ê³„ì •. */
	private AccountVo account;

	/** ì½”ë©˜?Š¸?‚´?š©. */
	private String commcontent;

	/** ì½”ë©˜?Š¸ê·¸ë£¹ë²ˆí˜¸. */
	private Integer commref;

	/** ì½”ë©˜?Š¸? ˆë²?. */
	private Integer commlev;

	/** ì½”ë©˜?Š¸ì¶œë ¥?ˆœ?„œ. */
	private Integer commstep;

	/**
	 * ?ƒ?„±?.
	 */
	public CommentVo() {
	}

	/**
	 * ì½”ë©˜?Š¸ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commnum
	 *            ì½”ë©˜?Š¸ë²ˆí˜¸
	 */
	public void setCommnum(Integer commnum) {
		this.commnum = commnum;
	}

	/**
	 * ì½”ë©˜?Š¸ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸ë²ˆí˜¸
	 */
	public Integer getCommnum() {
		return this.commnum;
	}

	/**
	 * ?Š¤?† ë¦¬ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param story
	 *            ?Š¤?† ë¦?
	 */
	public void setStory(StoryVo story) {
		this.story = story;
	}

	/**
	 * ?Š¤?† ë¦¬ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¤?† ë¦?
	 */
	public StoryVo getStory() {
		return this.story;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ì½”ë©˜?Š¸?‚´?š©?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commcontent
	 *            ì½”ë©˜?Š¸?‚´?š©
	 */
	public void setCommcontent(String commcontent) {
		this.commcontent = commcontent;
	}

	/**
	 * ì½”ë©˜?Š¸?‚´?š©?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸?‚´?š©
	 */
	public String getCommcontent() {
		return this.commcontent;
	}

	/**
	 * ì½”ë©˜?Š¸ê·¸ë£¹ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commref
	 *            ì½”ë©˜?Š¸ê·¸ë£¹ë²ˆí˜¸
	 */
	public void setCommref(Integer commref) {
		this.commref = commref;
	}

	/**
	 * ì½”ë©˜?Š¸ê·¸ë£¹ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸ê·¸ë£¹ë²ˆí˜¸
	 */
	public Integer getCommref() {
		return this.commref;
	}

	/**
	 * ì½”ë©˜?Š¸? ˆë²¨ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commlev
	 *            ì½”ë©˜?Š¸? ˆë²?
	 */
	public void setCommlev(Integer commlev) {
		this.commlev = commlev;
	}

	/**
	 * ì½”ë©˜?Š¸? ˆë²¨ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸? ˆë²?
	 */
	public Integer getCommlev() {
		return this.commlev;
	}

	/**
	 * ì½”ë©˜?Š¸ì¶œë ¥?ˆœ?„œ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commstep
	 *            ì½”ë©˜?Š¸ì¶œë ¥?ˆœ?„œ
	 */
	public void setCommstep(Integer commstep) {
		this.commstep = commstep;
	}

	/**
	 * ì½”ë©˜?Š¸ì¶œë ¥?ˆœ?„œ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸ì¶œë ¥?ˆœ?„œ
	 */
	public Integer getCommstep() {
		return this.commstep;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commnum == null) ? 0 : commnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommentVo other = (CommentVo) obj;
		if (commnum == null) {
			if (other.commnum != null) {
				return false;
			}
		} else if (!commnum.equals(other.commnum)) {
			return false;
		}
		return true;
	}

}
