package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 코멘트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentsVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코멘트번호. */
	private Integer commnum;

	/** 스토리. */
	private StoryVo story;

	/** 계정. */
	private AccountVo account;

	/** 코멘트내용. */
	private String commcontent;

	/** 코멘트그룹번호. */
	private Integer commref;

	/** 코멘트레벨. */
	private Integer commlev;

	/** 코멘트출력순서. */
	private Integer commstep;

	/**
	 * 생성자.
	 */
	public CommentsVo() {
	}

	/**
	 * 코멘트번호을 설정합니다..
	 * 
	 * @param commnum
	 *            코멘트번호
	 */
	public void setCommnum(Integer commnum) {
		this.commnum = commnum;
	}

	/**
	 * 코멘트번호을 가져옵니다..
	 * 
	 * @return 코멘트번호
	 */
	public Integer getCommnum() {
		return this.commnum;
	}

	/**
	 * 스토리을 설정합니다..
	 * 
	 * @param story
	 *            스토리
	 */
	public void setStory(StoryVo story) {
		this.story = story;
	}

	/**
	 * 스토리을 가져옵니다..
	 * 
	 * @return 스토리
	 */
	public StoryVo getStory() {
		return this.story;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * 코멘트내용을 설정합니다..
	 * 
	 * @param commcontent
	 *            코멘트내용
	 */
	public void setCommcontent(String commcontent) {
		this.commcontent = commcontent;
	}

	/**
	 * 코멘트내용을 가져옵니다..
	 * 
	 * @return 코멘트내용
	 */
	public String getCommcontent() {
		return this.commcontent;
	}

	/**
	 * 코멘트그룹번호을 설정합니다..
	 * 
	 * @param commref
	 *            코멘트그룹번호
	 */
	public void setCommref(Integer commref) {
		this.commref = commref;
	}

	/**
	 * 코멘트그룹번호을 가져옵니다..
	 * 
	 * @return 코멘트그룹번호
	 */
	public Integer getCommref() {
		return this.commref;
	}

	/**
	 * 코멘트레벨을 설정합니다..
	 * 
	 * @param commlev
	 *            코멘트레벨
	 */
	public void setCommlev(Integer commlev) {
		this.commlev = commlev;
	}

	/**
	 * 코멘트레벨을 가져옵니다..
	 * 
	 * @return 코멘트레벨
	 */
	public Integer getCommlev() {
		return this.commlev;
	}

	/**
	 * 코멘트출력순서을 설정합니다..
	 * 
	 * @param commstep
	 *            코멘트출력순서
	 */
	public void setCommstep(Integer commstep) {
		this.commstep = commstep;
	}

	/**
	 * 코멘트출력순서을 가져옵니다..
	 * 
	 * @return 코멘트출력순서
	 */
	public Integer getCommstep() {
		return this.commstep;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commnum == null) ? 0 : commnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommentsVo other = (CommentsVo) obj;
		if (commnum == null) {
			if (other.commnum != null) {
				return false;
			}
		} else if (!commnum.equals(other.commnum)) {
			return false;
		}
		return true;
	}

}
