package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ?´ëª¨í‹°ì½˜ìƒµ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmoshopVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?´ëª¨í‹°ì½˜ê·¸ë£¹ë²ˆ?˜¸. */
	private Integer emognum;

	/** ê°?ê²?. */
	private Integer price;

	/** ?´ëª¨í‹°ì½˜ê·¸ë£¹ì´ë¦?. */
	private String name;

	/** ì¹´í…Œê³ ë¦¬. */
	private String category;

	/** ?´ëª¨í‹°ì½? ëª©ë¡. */
	private Set<EmoticonVo> emoticonSet;

	/** ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡. */
	private Set<EmoticongroupVo> emoticongroupSet;

	/** ì°œëª©ë¡? ëª©ë¡. */
	private Set<FavorlistVo> favorlistSet;

	/** ?„ ë¬? ëª©ë¡. */
	private Set<PresentVo> presentSet;

	/**
	 * ?ƒ?„±?.
	 */
	public EmoshopVo() {
		this.emoticonSet = new HashSet<EmoticonVo>();
		this.emoticongroupSet = new HashSet<EmoticongroupVo>();
		this.favorlistSet = new HashSet<FavorlistVo>();
		this.presentSet = new HashSet<PresentVo>();
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emognum
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£¹ë²ˆ?˜¸
	 */
	public void setEmognum(Integer emognum) {
		this.emognum = emognum;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ê·¸ë£¹ë²ˆ?˜¸
	 */
	public Integer getEmognum() {
		return this.emognum;
	}

	/**
	 * ê°?ê²©ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param price
	 *            ê°?ê²?
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * ê°?ê²©ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê°?ê²?
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ì´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param name
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£¹ì´ë¦?
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ì´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ê·¸ë£¹ì´ë¦?
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * ì¹´í…Œê³ ë¦¬?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param category
	 *            ì¹´í…Œê³ ë¦¬
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * ì¹´í…Œê³ ë¦¬?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì¹´í…Œê³ ë¦¬
	 */
	public String getCategory() {
		return this.category;
	}

	/**
	 * ?´ëª¨í‹°ì½? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoticonSet
	 *            ?´ëª¨í‹°ì½? ëª©ë¡
	 */
	public void setEmoticonSet(Set<EmoticonVo> emoticonSet) {
		this.emoticonSet = emoticonSet;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param emoticon
	 *            ?´ëª¨í‹°ì½?
	 */
	public void addEmoticon(EmoticonVo emoticon) {
		this.emoticonSet.add(emoticon);
	}

	/**
	 * ?´ëª¨í‹°ì½? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½? ëª©ë¡
	 */
	public Set<EmoticonVo> getEmoticonSet() {
		return this.emoticonSet;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoticongroupSet
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡
	 */
	public void setEmoticongroupSet(Set<EmoticongroupVo> emoticongroupSet) {
		this.emoticongroupSet = emoticongroupSet;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£¹ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param emoticongroup
	 *            ?´ëª¨í‹°ì½˜ê·¸ë£?
	 */
	public void addEmoticongroup(EmoticongroupVo emoticongroup) {
		this.emoticongroupSet.add(emoticongroup);
	}

	/**
	 * ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ê·¸ë£? ëª©ë¡
	 */
	public Set<EmoticongroupVo> getEmoticongroupSet() {
		return this.emoticongroupSet;
	}

	/**
	 * ì°œëª©ë¡? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favorlistSet
	 *            ì°œëª©ë¡? ëª©ë¡
	 */
	public void setFavorlistSet(Set<FavorlistVo> favorlistSet) {
		this.favorlistSet = favorlistSet;
	}

	/**
	 * ì°œëª©ë¡ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param favorlist
	 *            ì°œëª©ë¡?
	 */
	public void addFavorlist(FavorlistVo favorlist) {
		this.favorlistSet.add(favorlist);
	}

	/**
	 * ì°œëª©ë¡? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°œëª©ë¡? ëª©ë¡
	 */
	public Set<FavorlistVo> getFavorlistSet() {
		return this.favorlistSet;
	}

	/**
	 * ?„ ë¬? ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param presentSet
	 *            ?„ ë¬? ëª©ë¡
	 */
	public void setPresentSet(Set<PresentVo> presentSet) {
		this.presentSet = presentSet;
	}

	/**
	 * ?„ ë¬¼ë?? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param present
	 *            ?„ ë¬?
	 */
	public void addPresent(PresentVo present) {
		this.presentSet.add(present);
	}

	/**
	 * ?„ ë¬? ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?„ ë¬? ëª©ë¡
	 */
	public Set<PresentVo> getPresentSet() {
		return this.presentSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emognum == null) ? 0 : emognum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmoshopVo other = (EmoshopVo) obj;
		if (emognum == null) {
			if (other.emognum != null) {
				return false;
			}
		} else if (!emognum.equals(other.emognum)) {
			return false;
		}
		return true;
	}

}
