package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ?´ëª¨í‹°ì½˜ê·¸ë£? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmoticongroupVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?´ëª¨í‹°ì½˜ìƒµ. */
	private EmoshopVo emoshop;

	/** ê³„ì •. */
	private AccountVo account;

	/**
	 * ?ƒ?„±?.
	 */
	public EmoticongroupVo() {
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoshop
	 *            ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emoshop == null) ? 0 : emoshop.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmoticongroupVo other = (EmoticongroupVo) obj;
		if (emoshop == null) {
			if (other.emoshop != null) {
				return false;
			}
		} else if (!emoshop.equals(other.emoshop)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
