package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;

/**
 * ?´ëª¨í‹°ì½? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmoticonVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?´ëª¨í‹°ì½˜ë²ˆ?˜¸. */
	private Integer emonum;

	/** ?´ëª¨í‹°ì½˜ìƒµ. */
	private EmoshopVo emoshop;

	/** ?´ëª¨í‹°ì½˜ì›ë³¸ì´ë¯¸ì?ëª?. */
	private String emoorgimg;

	/** ?´ëª¨í‹°ì½˜ì??¥?´ë¯¸ì?ëª?. */
	private String emosaveimg;

	/** ?´ëª¨í‹°ì½˜íŒŒ?¼?¬ê¸?. */
	private Blob emoimgsize;

	/**
	 * ?ƒ?„±?.
	 */
	public EmoticonVo() {
	}

	/**
	 * ?´ëª¨í‹°ì½˜ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emonum
	 *            ?´ëª¨í‹°ì½˜ë²ˆ?˜¸
	 */
	public void setEmonum(Integer emonum) {
		this.emonum = emonum;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ë²ˆ?˜¸
	 */
	public Integer getEmonum() {
		return this.emonum;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoshop
	 *            ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ì›ë³¸ì´ë¯¸ì?ëª…ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoorgimg
	 *            ?´ëª¨í‹°ì½˜ì›ë³¸ì´ë¯¸ì?ëª?
	 */
	public void setEmoorgimg(String emoorgimg) {
		this.emoorgimg = emoorgimg;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ì›ë³¸ì´ë¯¸ì?ëª…ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ì›ë³¸ì´ë¯¸ì?ëª?
	 */
	public String getEmoorgimg() {
		return this.emoorgimg;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ì??¥?´ë¯¸ì?ëª…ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emosaveimg
	 *            ?´ëª¨í‹°ì½˜ì??¥?´ë¯¸ì?ëª?
	 */
	public void setEmosaveimg(String emosaveimg) {
		this.emosaveimg = emosaveimg;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ì??¥?´ë¯¸ì?ëª…ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ì??¥?´ë¯¸ì?ëª?
	 */
	public String getEmosaveimg() {
		return this.emosaveimg;
	}

	/**
	 * ?´ëª¨í‹°ì½˜íŒŒ?¼?¬ê¸°ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoimgsize
	 *            ?´ëª¨í‹°ì½˜íŒŒ?¼?¬ê¸?
	 */
	public void setEmoimgsize(Blob emoimgsize) {
		this.emoimgsize = emoimgsize;
	}

	/**
	 * ?´ëª¨í‹°ì½˜íŒŒ?¼?¬ê¸°ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜íŒŒ?¼?¬ê¸?
	 */
	public Blob getEmoimgsize() {
		return this.emoimgsize;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emonum == null) ? 0 : emonum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmoticonVo other = (EmoticonVo) obj;
		if (emonum == null) {
			if (other.emonum != null) {
				return false;
			}
		} else if (!emonum.equals(other.emonum)) {
			return false;
		}
		return true;
	}

}
