package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;

/**
 * 이모티콘 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmoticonVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 이모티콘번호. */
	private Integer emonum;

	/** 이모티콘샵. */
	private EmoshopVo emoshop;

	/** 이모티콘원본이미지명. */
	private String emoorgimg;

	/** 이모티콘저장이미지명. */
	private String emosaveimg;

	/** 이모티콘파일크기. */
	private Blob emoimgsize;

	/**
	 * 생성자.
	 */
	public EmoticonVo() {
	}

	/**
	 * 이모티콘번호을 설정합니다..
	 * 
	 * @param emonum
	 *            이모티콘번호
	 */
	public void setEmonum(Integer emonum) {
		this.emonum = emonum;
	}

	/**
	 * 이모티콘번호을 가져옵니다..
	 * 
	 * @return 이모티콘번호
	 */
	public Integer getEmonum() {
		return this.emonum;
	}

	/**
	 * 이모티콘샵을 설정합니다..
	 * 
	 * @param emoshop
	 *            이모티콘샵
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * 이모티콘샵을 가져옵니다..
	 * 
	 * @return 이모티콘샵
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * 이모티콘원본이미지명을 설정합니다..
	 * 
	 * @param emoorgimg
	 *            이모티콘원본이미지명
	 */
	public void setEmoorgimg(String emoorgimg) {
		this.emoorgimg = emoorgimg;
	}

	/**
	 * 이모티콘원본이미지명을 가져옵니다..
	 * 
	 * @return 이모티콘원본이미지명
	 */
	public String getEmoorgimg() {
		return this.emoorgimg;
	}

	/**
	 * 이모티콘저장이미지명을 설정합니다..
	 * 
	 * @param emosaveimg
	 *            이모티콘저장이미지명
	 */
	public void setEmosaveimg(String emosaveimg) {
		this.emosaveimg = emosaveimg;
	}

	/**
	 * 이모티콘저장이미지명을 가져옵니다..
	 * 
	 * @return 이모티콘저장이미지명
	 */
	public String getEmosaveimg() {
		return this.emosaveimg;
	}

	/**
	 * 이모티콘파일크기을 설정합니다..
	 * 
	 * @param emoimgsize
	 *            이모티콘파일크기
	 */
	public void setEmoimgsize(Blob emoimgsize) {
		this.emoimgsize = emoimgsize;
	}

	/**
	 * 이모티콘파일크기을 가져옵니다..
	 * 
	 * @return 이모티콘파일크기
	 */
	public Blob getEmoimgsize() {
		return this.emoimgsize;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emonum == null) ? 0 : emonum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmoticonVo other = (EmoticonVo) obj;
		if (emonum == null) {
			if (other.emonum != null) {
				return false;
			}
		} else if (!emonum.equals(other.emonum)) {
			return false;
		}
		return true;
	}

}
