package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 이모티콘그룹 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmoticongroupVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 이모티콘샵. */
	private EmoshopVo emoshop;

	/** 계정. */
	private AccountVo account;

	/**
	 * 생성자.
	 */
	public EmoticongroupVo() {
	}

	/**
	 * 이모티콘샵을 설정합니다..
	 * 
	 * @param emoshop
	 *            이모티콘샵
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * 이모티콘샵을 가져옵니다..
	 * 
	 * @return 이모티콘샵
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((emoshop == null) ? 0 : emoshop.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmoticongroupVo other = (EmoticongroupVo) obj;
		if (emoshop == null) {
			if (other.emoshop != null) {
				return false;
			}
		} else if (!emoshop.equals(other.emoshop)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
