package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ì°œëª©ë¡? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FavorlistVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì°œë²ˆ?˜¸. */
	private Integer favornum;

	/** ì°?. */
	private Integer favor;

	/** ?´ëª¨í‹°ì½˜ìƒµ. */
	private EmoshopVo emoshop;

	/** ê³„ì •. */
	private AccountVo account;

	/**
	 * ?ƒ?„±?.
	 */
	public FavorlistVo() {
	}

	/**
	 * ì°œë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favornum
	 *            ì°œë²ˆ?˜¸
	 */
	public void setFavornum(Integer favornum) {
		this.favornum = favornum;
	}

	/**
	 * ì°œë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°œë²ˆ?˜¸
	 */
	public Integer getFavornum() {
		return this.favornum;
	}

	/**
	 * ì°œì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favor
	 *            ì°?
	 */
	public void setFavor(Integer favor) {
		this.favor = favor;
	}

	/**
	 * ì°œì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°?
	 */
	public Integer getFavor() {
		return this.favor;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoshop
	 *            ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((favornum == null) ? 0 : favornum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FavorlistVo other = (FavorlistVo) obj;
		if (favornum == null) {
			if (other.favornum != null) {
				return false;
			}
		} else if (!favornum.equals(other.favornum)) {
			return false;
		}
		return true;
	}

}
