package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 찜목록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FavorlistVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 찜번호. */
	private Integer favornum;

	/** 찜. */
	private Integer favor;

	/** 이모티콘샵. */
	private EmoshopVo emoshop;

	/** 계정. */
	private AccountVo account;

	/**
	 * 생성자.
	 */
	public FavorlistVo() {
	}

	/**
	 * 찜번호을 설정합니다..
	 * 
	 * @param favornum
	 *            찜번호
	 */
	public void setFavornum(Integer favornum) {
		this.favornum = favornum;
	}

	/**
	 * 찜번호을 가져옵니다..
	 * 
	 * @return 찜번호
	 */
	public Integer getFavornum() {
		return this.favornum;
	}

	/**
	 * 찜을 설정합니다..
	 * 
	 * @param favor
	 *            찜
	 */
	public void setFavor(Integer favor) {
		this.favor = favor;
	}

	/**
	 * 찜을 가져옵니다..
	 * 
	 * @return 찜
	 */
	public Integer getFavor() {
		return this.favor;
	}

	/**
	 * 이모티콘샵을 설정합니다..
	 * 
	 * @param emoshop
	 *            이모티콘샵
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * 이모티콘샵을 가져옵니다..
	 * 
	 * @return 이모티콘샵
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((favornum == null) ? 0 : favornum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FavorlistVo other = (FavorlistVo) obj;
		if (favornum == null) {
			if (other.favornum != null) {
				return false;
			}
		} else if (!favornum.equals(other.favornum)) {
			return false;
		}
		return true;
	}

}
