package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ì¹œêµ¬ëª©ë¡ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FriendlistVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ê³„ì •. */
	private AccountVo account;

	/** ì¹œêµ¬ë²ˆí˜¸. */
	private Integer fnum;

	/** ì¦ê²¨ì°¾ê¸°. */
	private Integer favo;

	/** ì°¨ë‹¨?—¬ë¶?. */
	private Integer spam;

	/** ?Š¹?¸?—¬ë¶?. */
	private Integer approv;

	/**
	 * ?ƒ?„±?.
	 */
	public FriendlistVo() {
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ì¹œêµ¬ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param fnum
	 *            ì¹œêµ¬ë²ˆí˜¸
	 */
	public void setFnum(Integer fnum) {
		this.fnum = fnum;
	}

	/**
	 * ì¹œêµ¬ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì¹œêµ¬ë²ˆí˜¸
	 */
	public Integer getFnum() {
		return this.fnum;
	}

	/**
	 * ì¦ê²¨ì°¾ê¸°?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param favo
	 *            ì¦ê²¨ì°¾ê¸°
	 */
	public void setFavo(Integer favo) {
		this.favo = favo;
	}

	/**
	 * ì¦ê²¨ì°¾ê¸°?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì¦ê²¨ì°¾ê¸°
	 */
	public Integer getFavo() {
		return this.favo;
	}

	/**
	 * ì°¨ë‹¨?—¬ë¶??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param spam
	 *            ì°¨ë‹¨?—¬ë¶?
	 */
	public void setSpam(Integer spam) {
		this.spam = spam;
	}

	/**
	 * ì°¨ë‹¨?—¬ë¶??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì°¨ë‹¨?—¬ë¶?
	 */
	public Integer getSpam() {
		return this.spam;
	}

	/**
	 * ?Š¹?¸?—¬ë¶??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param approv
	 *            ?Š¹?¸?—¬ë¶?
	 */
	public void setApprov(Integer approv) {
		this.approv = approv;
	}

	/**
	 * ?Š¹?¸?—¬ë¶??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¹?¸?—¬ë¶?
	 */
	public Integer getApprov() {
		return this.approv;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		result = prime * result + ((fnum == null) ? 0 : fnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FriendlistVo other = (FriendlistVo) obj;
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		if (fnum == null) {
			if (other.fnum != null) {
				return false;
			}
		} else if (!fnum.equals(other.fnum)) {
			return false;
		}
		return true;
	}

}
