package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * êµ?ê°?ê¸°ë…?¼ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NationaldayVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ê¸°ë…?¼ë²ˆí˜¸. */
	private Integer anivernum;

	/** ê¸°ë…?¼?´ë¦?. */
	private String anivername;

	/** ê¸°ë…?¼?‚ ì§?. */
	private Date aniverregdate;

	/** ê¸°ë…?¼?‚´?š©. */
	private String anivercontent;

	/**
	 * ?ƒ?„±?.
	 */
	public NationaldayVo() {
	}

	/**
	 * ê¸°ë…?¼ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param anivernum
	 *            ê¸°ë…?¼ë²ˆí˜¸
	 */
	public void setAnivernum(Integer anivernum) {
		this.anivernum = anivernum;
	}

	/**
	 * ê¸°ë…?¼ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê¸°ë…?¼ë²ˆí˜¸
	 */
	public Integer getAnivernum() {
		return this.anivernum;
	}

	/**
	 * ê¸°ë…?¼?´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param anivername
	 *            ê¸°ë…?¼?´ë¦?
	 */
	public void setAnivername(String anivername) {
		this.anivername = anivername;
	}

	/**
	 * ê¸°ë…?¼?´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê¸°ë…?¼?´ë¦?
	 */
	public String getAnivername() {
		return this.anivername;
	}

	/**
	 * ê¸°ë…?¼?‚ ì§œì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param aniverregdate
	 *            ê¸°ë…?¼?‚ ì§?
	 */
	public void setAniverregdate(Date aniverregdate) {
		this.aniverregdate = aniverregdate;
	}

	/**
	 * ê¸°ë…?¼?‚ ì§œì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê¸°ë…?¼?‚ ì§?
	 */
	public Date getAniverregdate() {
		return this.aniverregdate;
	}

	/**
	 * ê¸°ë…?¼?‚´?š©?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param anivercontent
	 *            ê¸°ë…?¼?‚´?š©
	 */
	public void setAnivercontent(String anivercontent) {
		this.anivercontent = anivercontent;
	}

	/**
	 * ê¸°ë…?¼?‚´?š©?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê¸°ë…?¼?‚´?š©
	 */
	public String getAnivercontent() {
		return this.anivercontent;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((anivernum == null) ? 0 : anivernum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NationaldayVo other = (NationaldayVo) obj;
		if (anivernum == null) {
			if (other.anivernum != null) {
				return false;
			}
		} else if (!anivernum.equals(other.anivernum)) {
			return false;
		}
		return true;
	}

}
