package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 국가기념일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NationaldayVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 기념일번호. */
	private Integer anivernum;

	/** 기념일이름. */
	private String anivername;

	/** 기념일날짜. */
	private Date aniverregdate;

	/** 기념일내용. */
	private String anivercontent;

	/**
	 * 생성자.
	 */
	public NationaldayVo() {
	}

	/**
	 * 기념일번호을 설정합니다..
	 * 
	 * @param anivernum
	 *            기념일번호
	 */
	public void setAnivernum(Integer anivernum) {
		this.anivernum = anivernum;
	}

	/**
	 * 기념일번호을 가져옵니다..
	 * 
	 * @return 기념일번호
	 */
	public Integer getAnivernum() {
		return this.anivernum;
	}

	/**
	 * 기념일이름을 설정합니다..
	 * 
	 * @param anivername
	 *            기념일이름
	 */
	public void setAnivername(String anivername) {
		this.anivername = anivername;
	}

	/**
	 * 기념일이름을 가져옵니다..
	 * 
	 * @return 기념일이름
	 */
	public String getAnivername() {
		return this.anivername;
	}

	/**
	 * 기념일날짜을 설정합니다..
	 * 
	 * @param aniverregdate
	 *            기념일날짜
	 */
	public void setAniverregdate(Date aniverregdate) {
		this.aniverregdate = aniverregdate;
	}

	/**
	 * 기념일날짜을 가져옵니다..
	 * 
	 * @return 기념일날짜
	 */
	public Date getAniverregdate() {
		return this.aniverregdate;
	}

	/**
	 * 기념일내용을 설정합니다..
	 * 
	 * @param anivercontent
	 *            기념일내용
	 */
	public void setAnivercontent(String anivercontent) {
		this.anivercontent = anivercontent;
	}

	/**
	 * 기념일내용을 가져옵니다..
	 * 
	 * @return 기념일내용
	 */
	public String getAnivercontent() {
		return this.anivercontent;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((anivernum == null) ? 0 : anivernum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NationaldayVo other = (NationaldayVo) obj;
		if (anivernum == null) {
			if (other.anivernum != null) {
				return false;
			}
		} else if (!anivernum.equals(other.anivernum)) {
			return false;
		}
		return true;
	}

}
