package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ?½???‚¬?Œ? •ë³? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NoticeVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ì±„íŒ…. */
	private ChatVo chat;

	/** ì±„íŒ…ë¦¬ìŠ¤?Š¸. */
	private ChatlistVo chatlist;

	/** ê³„ì •. */
	private AccountVo account;

	/**
	 * ?ƒ?„±?.
	 */
	public NoticeVo() {
	}

	/**
	 * ì±„íŒ…?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chat
	 *            ì±„íŒ…
	 */
	public void setChat(ChatVo chat) {
		this.chat = chat;
	}

	/**
	 * ì±„íŒ…?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…
	 */
	public ChatVo getChat() {
		return this.chat;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param chatlist
	 *            ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public void setChatlist(ChatlistVo chatlist) {
		this.chatlist = chatlist;
	}

	/**
	 * ì±„íŒ…ë¦¬ìŠ¤?Š¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì±„íŒ…ë¦¬ìŠ¤?Š¸
	 */
	public ChatlistVo getChatlist() {
		return this.chatlist;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chat == null) ? 0 : chat.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NoticeVo other = (NoticeVo) obj;
		if (chat == null) {
			if (other.chat != null) {
				return false;
			}
		} else if (!chat.equals(other.chat)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
