package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 공지사항 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NoticeVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 공지사항번호. */
	private Integer noticenum;

	/** 공지사항제목. */
	private String noticetitle;

	/** 공지사항내용. */
	private String noticecontent;

	/** 공지사항작성일자. */
	private Date noticeregdate;

	/** 공지사항상태. */
	private Integer noticestate;

	/**
	 * 생성자.
	 */
	public NoticeVo() {
	}

	/**
	 * 공지사항번호을 설정합니다..
	 * 
	 * @param noticenum
	 *            공지사항번호
	 */
	public void setNoticenum(Integer noticenum) {
		this.noticenum = noticenum;
	}

	/**
	 * 공지사항번호을 가져옵니다..
	 * 
	 * @return 공지사항번호
	 */
	public Integer getNoticenum() {
		return this.noticenum;
	}

	/**
	 * 공지사항제목을 설정합니다..
	 * 
	 * @param noticetitle
	 *            공지사항제목
	 */
	public void setNoticetitle(String noticetitle) {
		this.noticetitle = noticetitle;
	}

	/**
	 * 공지사항제목을 가져옵니다..
	 * 
	 * @return 공지사항제목
	 */
	public String getNoticetitle() {
		return this.noticetitle;
	}

	/**
	 * 공지사항내용을 설정합니다..
	 * 
	 * @param noticecontent
	 *            공지사항내용
	 */
	public void setNoticecontent(String noticecontent) {
		this.noticecontent = noticecontent;
	}

	/**
	 * 공지사항내용을 가져옵니다..
	 * 
	 * @return 공지사항내용
	 */
	public String getNoticecontent() {
		return this.noticecontent;
	}

	/**
	 * 공지사항작성일자을 설정합니다..
	 * 
	 * @param noticeregdate
	 *            공지사항작성일자
	 */
	public void setNoticeregdate(Date noticeregdate) {
		this.noticeregdate = noticeregdate;
	}

	/**
	 * 공지사항작성일자을 가져옵니다..
	 * 
	 * @return 공지사항작성일자
	 */
	public Date getNoticeregdate() {
		return this.noticeregdate;
	}

	/**
	 * 공지사항상태을 설정합니다..
	 * 
	 * @param noticestate
	 *            공지사항상태
	 */
	public void setNoticestate(Integer noticestate) {
		this.noticestate = noticestate;
	}

	/**
	 * 공지사항상태을 가져옵니다..
	 * 
	 * @return 공지사항상태
	 */
	public Integer getNoticestate() {
		return this.noticestate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((noticenum == null) ? 0 : noticenum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NoticeVo other = (NoticeVo) obj;
		if (noticenum == null) {
			if (other.noticenum != null) {
				return false;
			}
		} else if (!noticenum.equals(other.noticenum)) {
			return false;
		}
		return true;
	}

}
