package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ?˜µ?…˜ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OptionVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?˜µ?…˜ë²ˆí˜¸. */
	private Integer optionnum;

	/** ê³„ì •. */
	private AccountVo account;

	/** ?°?Š¸?¬ê¸?. */
	private Integer fontsize;

	/** ?…Œë§?. */
	private String theme;

	/**
	 * ?ƒ?„±?.
	 */
	public OptionVo() {
	}

	/**
	 * ?˜µ?…˜ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param optionnum
	 *            ?˜µ?…˜ë²ˆí˜¸
	 */
	public void setOptionnum(Integer optionnum) {
		this.optionnum = optionnum;
	}

	/**
	 * ?˜µ?…˜ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?˜µ?…˜ë²ˆí˜¸
	 */
	public Integer getOptionnum() {
		return this.optionnum;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ?°?Š¸?¬ê¸°ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param fontsize
	 *            ?°?Š¸?¬ê¸?
	 */
	public void setFontsize(Integer fontsize) {
		this.fontsize = fontsize;
	}

	/**
	 * ?°?Š¸?¬ê¸°ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?°?Š¸?¬ê¸?
	 */
	public Integer getFontsize() {
		return this.fontsize;
	}

	/**
	 * ?…Œë§ˆì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param theme
	 *            ?…Œë§?
	 */
	public void setTheme(String theme) {
		this.theme = theme;
	}

	/**
	 * ?…Œë§ˆì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?…Œë§?
	 */
	public String getTheme() {
		return this.theme;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((optionnum == null) ? 0 : optionnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OptionVo other = (OptionVo) obj;
		if (optionnum == null) {
			if (other.optionnum != null) {
				return false;
			}
		} else if (!optionnum.equals(other.optionnum)) {
			return false;
		}
		return true;
	}

}
