package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 옵션 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OptionsVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 옵션번호. */
	private Integer optionnum;

	/** 계정. */
	private AccountVo account;

	/** 폰트크기. */
	private Integer fontsize;

	/** 테마. */
	private String theme;

	/**
	 * 생성자.
	 */
	public OptionsVo() {
	}

	/**
	 * 옵션번호을 설정합니다..
	 * 
	 * @param optionnum
	 *            옵션번호
	 */
	public void setOptionnum(Integer optionnum) {
		this.optionnum = optionnum;
	}

	/**
	 * 옵션번호을 가져옵니다..
	 * 
	 * @return 옵션번호
	 */
	public Integer getOptionnum() {
		return this.optionnum;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * 폰트크기을 설정합니다..
	 * 
	 * @param fontsize
	 *            폰트크기
	 */
	public void setFontsize(Integer fontsize) {
		this.fontsize = fontsize;
	}

	/**
	 * 폰트크기을 가져옵니다..
	 * 
	 * @return 폰트크기
	 */
	public Integer getFontsize() {
		return this.fontsize;
	}

	/**
	 * 테마을 설정합니다..
	 * 
	 * @param theme
	 *            테마
	 */
	public void setTheme(String theme) {
		this.theme = theme;
	}

	/**
	 * 테마을 가져옵니다..
	 * 
	 * @return 테마
	 */
	public String getTheme() {
		return this.theme;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((optionnum == null) ? 0 : optionnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OptionsVo other = (OptionsVo) obj;
		if (optionnum == null) {
			if (other.optionnum != null) {
				return false;
			}
		} else if (!optionnum.equals(other.optionnum)) {
			return false;
		}
		return true;
	}

}
