package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * ?„ ë¬? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PresentVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?„ ë¬¼ë²ˆ?˜¸. */
	private Integer presnum;

	/** ?´ëª¨í‹°ì½˜ìƒµ. */
	private EmoshopVo emoshop;

	/** ê³„ì •. */
	private AccountVo gaccount;

	/** ê³„ì •. */
	private AccountVo raccount;

	/**
	 * ?ƒ?„±?.
	 */
	public PresentVo() {
	}

	/**
	 * ?„ ë¬¼ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param presnum
	 *            ?„ ë¬¼ë²ˆ?˜¸
	 */
	public void setPresnum(Integer presnum) {
		this.presnum = presnum;
	}

	/**
	 * ?„ ë¬¼ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?„ ë¬¼ë²ˆ?˜¸
	 */
	public Integer getPresnum() {
		return this.presnum;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param emoshop
	 *            ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * ?´ëª¨í‹°ì½˜ìƒµ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ëª¨í‹°ì½˜ìƒµ
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param gaccount
	 *            ê³„ì •
	 */
	public void setGaccount(AccountVo gaccount) {
		this.gaccount = gaccount;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getGaccount() {
		return this.gaccount;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param raccount
	 *            ê³„ì •
	 */
	public void setRaccount(AccountVo raccount) {
		this.raccount = raccount;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getRaccount() {
		return this.raccount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((presnum == null) ? 0 : presnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PresentVo other = (PresentVo) obj;
		if (presnum == null) {
			if (other.presnum != null) {
				return false;
			}
		} else if (!presnum.equals(other.presnum)) {
			return false;
		}
		return true;
	}

}
