package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 선물 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PresentVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 선물번호. */
	private Integer presnum;

	/** 이모티콘샵. */
	private EmoshopVo emoshop;

	/** 계정. */
	private AccountVo gaccount;

	/** 계정. */
	private AccountVo raccount;

	/**
	 * 생성자.
	 */
	public PresentVo() {
	}

	/**
	 * 선물번호을 설정합니다..
	 * 
	 * @param presnum
	 *            선물번호
	 */
	public void setPresnum(Integer presnum) {
		this.presnum = presnum;
	}

	/**
	 * 선물번호을 가져옵니다..
	 * 
	 * @return 선물번호
	 */
	public Integer getPresnum() {
		return this.presnum;
	}

	/**
	 * 이모티콘샵을 설정합니다..
	 * 
	 * @param emoshop
	 *            이모티콘샵
	 */
	public void setEmoshop(EmoshopVo emoshop) {
		this.emoshop = emoshop;
	}

	/**
	 * 이모티콘샵을 가져옵니다..
	 * 
	 * @return 이모티콘샵
	 */
	public EmoshopVo getEmoshop() {
		return this.emoshop;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param gaccount
	 *            계정
	 */
	public void setGaccount(AccountVo gaccount) {
		this.gaccount = gaccount;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getGaccount() {
		return this.gaccount;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param raccount
	 *            계정
	 */
	public void setRaccount(AccountVo raccount) {
		this.raccount = raccount;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getRaccount() {
		return this.raccount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((presnum == null) ? 0 : presnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PresentVo other = (PresentVo) obj;
		if (presnum == null) {
			if (other.presnum != null) {
				return false;
			}
		} else if (!presnum.equals(other.presnum)) {
			return false;
		}
		return true;
	}

}
