package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 프로필 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProfilesVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 계정. */
	private AccountVo account;

	/** 이름. */
	private String name;

	/** 전화번호. */
	private String phone;

	/** 메일주소. */
	private String email;

	/** 생년월일. */
	private Date birth;

	/** 프로필이미지. */
	private String profileimg;

	/** 배경이미지. */
	private String backimg;

	/** 상태메시지. */
	private String msg;

	/**
	 * 생성자.
	 */
	public ProfilesVo() {
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param name
	 *            이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 전화번호을 설정합니다..
	 * 
	 * @param phone
	 *            전화번호
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * 전화번호을 가져옵니다..
	 * 
	 * @return 전화번호
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * 메일주소을 설정합니다..
	 * 
	 * @param email
	 *            메일주소
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 메일주소을 가져옵니다..
	 * 
	 * @return 메일주소
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 생년월일을 설정합니다..
	 * 
	 * @param birth
	 *            생년월일
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * 생년월일을 가져옵니다..
	 * 
	 * @return 생년월일
	 */
	public Date getBirth() {
		return this.birth;
	}

	/**
	 * 프로필이미지을 설정합니다..
	 * 
	 * @param profileimg
	 *            프로필이미지
	 */
	public void setProfileimg(String profileimg) {
		this.profileimg = profileimg;
	}

	/**
	 * 프로필이미지을 가져옵니다..
	 * 
	 * @return 프로필이미지
	 */
	public String getProfileimg() {
		return this.profileimg;
	}

	/**
	 * 배경이미지을 설정합니다..
	 * 
	 * @param backimg
	 *            배경이미지
	 */
	public void setBackimg(String backimg) {
		this.backimg = backimg;
	}

	/**
	 * 배경이미지을 가져옵니다..
	 * 
	 * @return 배경이미지
	 */
	public String getBackimg() {
		return this.backimg;
	}

	/**
	 * 상태메시지을 설정합니다..
	 * 
	 * @param msg
	 *            상태메시지
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * 상태메시지을 가져옵니다..
	 * 
	 * @return 상태메시지
	 */
	public String getMsg() {
		return this.msg;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProfilesVo other = (ProfilesVo) obj;
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
