package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * ?”„ë¡œí•„ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProfileVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ê³„ì •. */
	private AccountVo account;

	/** ?´ë¦?. */
	private String name;

	/** ? „?™”ë²ˆí˜¸. */
	private String phone;

	/** ë©”ì¼ì£¼ì†Œ. */
	private String email;

	/** ?ƒ?…„?›”?¼. */
	private Date birth;

	/** ?”„ë¡œí•„?´ë¯¸ì?. */
	private String profileimg;

	/** ë°°ê²½?´ë¯¸ì?. */
	private String backimg;

	/** ?ƒ?ƒœë©”ì‹œì§?. */
	private String msg;

	/**
	 * ?ƒ?„±?.
	 */
	public ProfileVo() {
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ?´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param name
	 *            ?´ë¦?
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * ?´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?´ë¦?
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * ? „?™”ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param phone
	 *            ? „?™”ë²ˆí˜¸
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * ? „?™”ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ? „?™”ë²ˆí˜¸
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * ë©”ì¼ì£¼ì†Œ?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param email
	 *            ë©”ì¼ì£¼ì†Œ
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * ë©”ì¼ì£¼ì†Œ?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë©”ì¼ì£¼ì†Œ
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * ?ƒ?…„?›”?¼?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param birth
	 *            ?ƒ?…„?›”?¼
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * ?ƒ?…„?›”?¼?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?ƒ?…„?›”?¼
	 */
	public Date getBirth() {
		return this.birth;
	}

	/**
	 * ?”„ë¡œí•„?´ë¯¸ì??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param profileimg
	 *            ?”„ë¡œí•„?´ë¯¸ì?
	 */
	public void setProfileimg(String profileimg) {
		this.profileimg = profileimg;
	}

	/**
	 * ?”„ë¡œí•„?´ë¯¸ì??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?”„ë¡œí•„?´ë¯¸ì?
	 */
	public String getProfileimg() {
		return this.profileimg;
	}

	/**
	 * ë°°ê²½?´ë¯¸ì??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param backimg
	 *            ë°°ê²½?´ë¯¸ì?
	 */
	public void setBackimg(String backimg) {
		this.backimg = backimg;
	}

	/**
	 * ë°°ê²½?´ë¯¸ì??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë°°ê²½?´ë¯¸ì?
	 */
	public String getBackimg() {
		return this.backimg;
	}

	/**
	 * ?ƒ?ƒœë©”ì‹œì§??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param msg
	 *            ?ƒ?ƒœë©”ì‹œì§?
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * ?ƒ?ƒœë©”ì‹œì§??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?ƒ?ƒœë©”ì‹œì§?
	 */
	public String getMsg() {
		return this.msg;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProfileVo other = (ProfileVo) obj;
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
