package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * ë¬¸ì˜ ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ë¬¸ì˜ë²ˆí˜¸. */
	private Integer qnanum;

	/** ê³„ì •. */
	private AccountVo account;

	/** ë¬¸ì˜ì¹´í…Œê³ ë¦¬. */
	private Integer qnacategory;

	/** ë¬¸ì˜? œëª?. */
	private String qnatitle;

	/** ë¬¸ì˜?‚´?š©. */
	private String qnacontent;

	/** ë¬¸ì˜?‘?„±?¼?. */
	private Date qnaregdate;

	/** ë¬¸ì˜?‹µë³?. */
	private String qnaanswer;

	/** ë¬¸ì˜?‹µë³??‘?„±?¼?. */
	private Date qnaqnswerregdate;

	/**
	 * ?ƒ?„±?.
	 */
	public QnaVo() {
	}

	/**
	 * ë¬¸ì˜ë²ˆí˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnanum
	 *            ë¬¸ì˜ë²ˆí˜¸
	 */
	public void setQnanum(Integer qnanum) {
		this.qnanum = qnanum;
	}

	/**
	 * ë¬¸ì˜ë²ˆí˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜ë²ˆí˜¸
	 */
	public Integer getQnanum() {
		return this.qnanum;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ë¬¸ì˜ì¹´í…Œê³ ë¦¬?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnacategory
	 *            ë¬¸ì˜ì¹´í…Œê³ ë¦¬
	 */
	public void setQnacategory(Integer qnacategory) {
		this.qnacategory = qnacategory;
	}

	/**
	 * ë¬¸ì˜ì¹´í…Œê³ ë¦¬?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜ì¹´í…Œê³ ë¦¬
	 */
	public Integer getQnacategory() {
		return this.qnacategory;
	}

	/**
	 * ë¬¸ì˜? œëª©ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnatitle
	 *            ë¬¸ì˜? œëª?
	 */
	public void setQnatitle(String qnatitle) {
		this.qnatitle = qnatitle;
	}

	/**
	 * ë¬¸ì˜? œëª©ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜? œëª?
	 */
	public String getQnatitle() {
		return this.qnatitle;
	}

	/**
	 * ë¬¸ì˜?‚´?š©?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnacontent
	 *            ë¬¸ì˜?‚´?š©
	 */
	public void setQnacontent(String qnacontent) {
		this.qnacontent = qnacontent;
	}

	/**
	 * ë¬¸ì˜?‚´?š©?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜?‚´?š©
	 */
	public String getQnacontent() {
		return this.qnacontent;
	}

	/**
	 * ë¬¸ì˜?‘?„±?¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnaregdate
	 *            ë¬¸ì˜?‘?„±?¼?
	 */
	public void setQnaregdate(Date qnaregdate) {
		this.qnaregdate = qnaregdate;
	}

	/**
	 * ë¬¸ì˜?‘?„±?¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜?‘?„±?¼?
	 */
	public Date getQnaregdate() {
		return this.qnaregdate;
	}

	/**
	 * ë¬¸ì˜?‹µë³??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnaanswer
	 *            ë¬¸ì˜?‹µë³?
	 */
	public void setQnaanswer(String qnaanswer) {
		this.qnaanswer = qnaanswer;
	}

	/**
	 * ë¬¸ì˜?‹µë³??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜?‹µë³?
	 */
	public String getQnaanswer() {
		return this.qnaanswer;
	}

	/**
	 * ë¬¸ì˜?‹µë³??‘?„±?¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param qnaqnswerregdate
	 *            ë¬¸ì˜?‹µë³??‘?„±?¼?
	 */
	public void setQnaqnswerregdate(Date qnaqnswerregdate) {
		this.qnaqnswerregdate = qnaqnswerregdate;
	}

	/**
	 * ë¬¸ì˜?‹µë³??‘?„±?¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ë¬¸ì˜?‹µë³??‘?„±?¼?
	 */
	public Date getQnaqnswerregdate() {
		return this.qnaqnswerregdate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qnanum == null) ? 0 : qnanum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QnaVo other = (QnaVo) obj;
		if (qnanum == null) {
			if (other.qnanum != null) {
				return false;
			}
		} else if (!qnanum.equals(other.qnanum)) {
			return false;
		}
		return true;
	}

}
