package fproject.app.fproject.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 문의 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 문의번호. */
	private Integer qnanum;

	/** 계정. */
	private AccountVo account;

	/** 문의카테고리. */
	private Integer qnacategory;

	/** 문의제목. */
	private String qnatitle;

	/** 문의내용. */
	private String qnacontent;

	/** 문의작성일자. */
	private Date qnaregdate;

	/** 문의답변. */
	private String qnaanswer;

	/** 문의답변작성일자. */
	private Date qnaqnswerregdate;

	/**
	 * 생성자.
	 */
	public QnaVo() {
	}

	/**
	 * 문의번호을 설정합니다..
	 * 
	 * @param qnanum
	 *            문의번호
	 */
	public void setQnanum(Integer qnanum) {
		this.qnanum = qnanum;
	}

	/**
	 * 문의번호을 가져옵니다..
	 * 
	 * @return 문의번호
	 */
	public Integer getQnanum() {
		return this.qnanum;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * 문의카테고리을 설정합니다..
	 * 
	 * @param qnacategory
	 *            문의카테고리
	 */
	public void setQnacategory(Integer qnacategory) {
		this.qnacategory = qnacategory;
	}

	/**
	 * 문의카테고리을 가져옵니다..
	 * 
	 * @return 문의카테고리
	 */
	public Integer getQnacategory() {
		return this.qnacategory;
	}

	/**
	 * 문의제목을 설정합니다..
	 * 
	 * @param qnatitle
	 *            문의제목
	 */
	public void setQnatitle(String qnatitle) {
		this.qnatitle = qnatitle;
	}

	/**
	 * 문의제목을 가져옵니다..
	 * 
	 * @return 문의제목
	 */
	public String getQnatitle() {
		return this.qnatitle;
	}

	/**
	 * 문의내용을 설정합니다..
	 * 
	 * @param qnacontent
	 *            문의내용
	 */
	public void setQnacontent(String qnacontent) {
		this.qnacontent = qnacontent;
	}

	/**
	 * 문의내용을 가져옵니다..
	 * 
	 * @return 문의내용
	 */
	public String getQnacontent() {
		return this.qnacontent;
	}

	/**
	 * 문의작성일자을 설정합니다..
	 * 
	 * @param qnaregdate
	 *            문의작성일자
	 */
	public void setQnaregdate(Date qnaregdate) {
		this.qnaregdate = qnaregdate;
	}

	/**
	 * 문의작성일자을 가져옵니다..
	 * 
	 * @return 문의작성일자
	 */
	public Date getQnaregdate() {
		return this.qnaregdate;
	}

	/**
	 * 문의답변을 설정합니다..
	 * 
	 * @param qnaanswer
	 *            문의답변
	 */
	public void setQnaanswer(String qnaanswer) {
		this.qnaanswer = qnaanswer;
	}

	/**
	 * 문의답변을 가져옵니다..
	 * 
	 * @return 문의답변
	 */
	public String getQnaanswer() {
		return this.qnaanswer;
	}

	/**
	 * 문의답변작성일자을 설정합니다..
	 * 
	 * @param qnaqnswerregdate
	 *            문의답변작성일자
	 */
	public void setQnaqnswerregdate(Date qnaqnswerregdate) {
		this.qnaqnswerregdate = qnaqnswerregdate;
	}

	/**
	 * 문의답변작성일자을 가져옵니다..
	 * 
	 * @return 문의답변작성일자
	 */
	public Date getQnaqnswerregdate() {
		return this.qnaqnswerregdate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qnanum == null) ? 0 : qnanum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QnaVo other = (QnaVo) obj;
		if (qnanum == null) {
			if (other.qnanum != null) {
				return false;
			}
		} else if (!qnanum.equals(other.qnanum)) {
			return false;
		}
		return true;
	}

}
