package fproject.app.fproject.vo;

import java.io.Serializable;

/**
 * 읽은사람정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReadinfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 채팅. */
	private ChatVo chat;

	/** 채팅리스트. */
	private ChatlistVo chatlist;

	/** 계정. */
	private AccountVo account;

	/**
	 * 생성자.
	 */
	public ReadinfoVo() {
	}

	/**
	 * 채팅을 설정합니다..
	 * 
	 * @param chat
	 *            채팅
	 */
	public void setChat(ChatVo chat) {
		this.chat = chat;
	}

	/**
	 * 채팅을 가져옵니다..
	 * 
	 * @return 채팅
	 */
	public ChatVo getChat() {
		return this.chat;
	}

	/**
	 * 채팅리스트을 설정합니다..
	 * 
	 * @param chatlist
	 *            채팅리스트
	 */
	public void setChatlist(ChatlistVo chatlist) {
		this.chatlist = chatlist;
	}

	/**
	 * 채팅리스트을 가져옵니다..
	 * 
	 * @return 채팅리스트
	 */
	public ChatlistVo getChatlist() {
		return this.chatlist;
	}

	/**
	 * 계정을 설정합니다..
	 * 
	 * @param account
	 *            계정
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * 계정을 가져옵니다..
	 * 
	 * @return 계정
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chat == null) ? 0 : chat.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReadinfoVo other = (ReadinfoVo) obj;
		if (chat == null) {
			if (other.chat != null) {
				return false;
			}
		} else if (!chat.equals(other.chat)) {
			return false;
		}
		if (account == null) {
			if (other.account != null) {
				return false;
			}
		} else if (!account.equals(other.account)) {
			return false;
		}
		return true;
	}

}
