package fproject.app.fproject.vo;

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ?Š¤?† ë¦? ëª¨ë¸ ?´?˜?Š¤.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StoryVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ?Š¤?† ë¦¬ë²ˆ?˜¸. */
	private Integer storynum;

	/** ê³„ì •. */
	private AccountVo account;

	/** ?Š¤?† ë¦¬ì œëª?. */
	private String stitle;

	/** ?Š¤?† ë¦¬ë‚´?š©. */
	private String scontent;

	/** ?‘?„±?¼?. */
	private Date sregdate;

	/** ?›ë³¸ì´ë¯¸ì??´ë¦?. */
	private String orgimg;

	/** ???¥?´ë¯¸ì??´ë¦?. */
	private String saveimg;

	/** ?ŒŒ?¼?¬ê¸?. */
	private Blob imgsize;

	/** ì½”ë©˜?Š¸ ëª©ë¡. */
	private Set<CommentVo> commentSet;

	/**
	 * ?ƒ?„±?.
	 */
	public StoryVo() {
		this.commentSet = new HashSet<CommentVo>();
	}

	/**
	 * ?Š¤?† ë¦¬ë²ˆ?˜¸?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param storynum
	 *            ?Š¤?† ë¦¬ë²ˆ?˜¸
	 */
	public void setStorynum(Integer storynum) {
		this.storynum = storynum;
	}

	/**
	 * ?Š¤?† ë¦¬ë²ˆ?˜¸?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¤?† ë¦¬ë²ˆ?˜¸
	 */
	public Integer getStorynum() {
		return this.storynum;
	}

	/**
	 * ê³„ì •?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param account
	 *            ê³„ì •
	 */
	public void setAccount(AccountVo account) {
		this.account = account;
	}

	/**
	 * ê³„ì •?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ê³„ì •
	 */
	public AccountVo getAccount() {
		return this.account;
	}

	/**
	 * ?Š¤?† ë¦¬ì œëª©ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param stitle
	 *            ?Š¤?† ë¦¬ì œëª?
	 */
	public void setStitle(String stitle) {
		this.stitle = stitle;
	}

	/**
	 * ?Š¤?† ë¦¬ì œëª©ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¤?† ë¦¬ì œëª?
	 */
	public String getStitle() {
		return this.stitle;
	}

	/**
	 * ?Š¤?† ë¦¬ë‚´?š©?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param scontent
	 *            ?Š¤?† ë¦¬ë‚´?š©
	 */
	public void setScontent(String scontent) {
		this.scontent = scontent;
	}

	/**
	 * ?Š¤?† ë¦¬ë‚´?š©?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?Š¤?† ë¦¬ë‚´?š©
	 */
	public String getScontent() {
		return this.scontent;
	}

	/**
	 * ?‘?„±?¼??„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param sregdate
	 *            ?‘?„±?¼?
	 */
	public void setSregdate(Date sregdate) {
		this.sregdate = sregdate;
	}

	/**
	 * ?‘?„±?¼??„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?‘?„±?¼?
	 */
	public Date getSregdate() {
		return this.sregdate;
	}

	/**
	 * ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param orgimg
	 *            ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public void setOrgimg(String orgimg) {
		this.orgimg = orgimg;
	}

	/**
	 * ?›ë³¸ì´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?›ë³¸ì´ë¯¸ì??´ë¦?
	 */
	public String getOrgimg() {
		return this.orgimg;
	}

	/**
	 * ???¥?´ë¯¸ì??´ë¦„ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param saveimg
	 *            ???¥?´ë¯¸ì??´ë¦?
	 */
	public void setSaveimg(String saveimg) {
		this.saveimg = saveimg;
	}

	/**
	 * ???¥?´ë¯¸ì??´ë¦„ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ???¥?´ë¯¸ì??´ë¦?
	 */
	public String getSaveimg() {
		return this.saveimg;
	}

	/**
	 * ?ŒŒ?¼?¬ê¸°ì„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param imgsize
	 *            ?ŒŒ?¼?¬ê¸?
	 */
	public void setImgsize(Blob imgsize) {
		this.imgsize = imgsize;
	}

	/**
	 * ?ŒŒ?¼?¬ê¸°ì„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ?ŒŒ?¼?¬ê¸?
	 */
	public Blob getImgsize() {
		return this.imgsize;
	}

	/**
	 * ì½”ë©˜?Š¸ ëª©ë¡?„ ?„¤? •?•©?‹ˆ?‹¤..
	 * 
	 * @param commentSet
	 *            ì½”ë©˜?Š¸ ëª©ë¡
	 */
	public void setCommentSet(Set<CommentVo> commentSet) {
		this.commentSet = commentSet;
	}

	/**
	 * ì½”ë©˜?Š¸ë¥? ì¶”ê??•©?‹ˆ?‹¤..
	 * 
	 * @param comment
	 *            ì½”ë©˜?Š¸
	 */
	public void addComment(CommentVo comment) {
		this.commentSet.add(comment);
	}

	/**
	 * ì½”ë©˜?Š¸ ëª©ë¡?„ ê°?? ¸?˜µ?‹ˆ?‹¤..
	 * 
	 * @return ì½”ë©˜?Š¸ ëª©ë¡
	 */
	public Set<CommentVo> getCommentSet() {
		return this.commentSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((storynum == null) ? 0 : storynum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StoryVo other = (StoryVo) obj;
		if (storynum == null) {
			if (other.storynum != null) {
				return false;
			}
		} else if (!storynum.equals(other.storynum)) {
			return false;
		}
		return true;
	}

}
